name = "Agutsin"
author = "Agustin Belizan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16b01e4f9a100198e633699500a76d6bf92585d66aee3b6bb8409059b1f62a6c"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
