name = "Agutsin"
author = "Agustin Belizan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16919815ee13464a42e4a590e0b8dbc0ec6c01f41fa30afaa489e029649cebac"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
